### ISSUE TITLE
Script does not open new tab in Macos version of Azure Data studio

### ISSUE THREAD

**Issue by patoJamriska** [pacoweb/extraSqlScriptAs#20] opened 2024-04-26 20:54 UTC
Insatlled the extension
tried opening the menu and select the insert option
nothing happens after.

**Comment by pacoweb** [comment] 2024-04-27 18:30
Unfortunately I can't reproduce the error because I don't have Macos. I will keep the incident open in case someone can help me. I'm sorry

**Comment by sunilred** [comment] 2024-05-27 04:45
Hi. Great extension idea but like Pato mentioned, it does not seem to work on MacOS (latest version). There are no error messages. Just nothing happens.
Happy to help with testing if you needed.

![2024-05-27 10 13 41](https://github.com/pacoweb/extraSqlScriptAs/assets/37816928/a8e278d5-7bda-43d2-9e24-19220b4c852d)

**Comment by sunilred** [comment] 2024-05-28 01:21
> Hi. Great extension idea but like Pato mentioned, it does not seem to work on MacOS (latest version). There are no error messages. Just nothing happens. Happy to help with testing if you needed.
> 


Hi. I just realised that the "Script table as DELETE" works but none of the other options work. So hopefully it is an easy fix.

**Comment by pacoweb** [comment] 2024-05-28 10:40
Thanks @patoJamriska and @sunilred
I´ll try find the issue. 
One question: any message in ouput window when operation fails?

**Comment by sunilred** [comment] 2024-05-28 12:52
Nothing appears in the output. If the command works, like the DELETE SCRIPT, then it appears in the output pane.

![2024-05-28 at 6 20 PM](https://github.com/pacoweb/extraSqlScriptAs/assets/37816928/7b1015b2-d922-4da7-8519-d21fbdc77356)

**Comment by pacoweb** [comment] 2024-05-29 05:58
Hi,
I have another question @patoJamriska and @sunilred
The clipboard´s options are working?
Thanks

**Comment by sunilred** [comment] 2024-05-29 06:37
The clipboard option is not working either except for the DELETE SCRIPT option.

**Comment by pacoweb** [comment] 2024-05-29 10:00
When you (@sunilred) can,  try this to see if we get more info in the output window

Set the log level to Trace and then see in the ouput window if there is more info

To change the log level, from the Command Palette (Ctrl/Cmd + Shift + P), run the Developer: Set Log Level... 
[Ref](https://learn.microsoft.com/en-us/azure-data-studio/troubleshooting#azure-data-studio)

Thank you so much!

**Comment by sunilred** [comment] 2024-05-29 11:07
I changed the log level to trace. The extension is now working fine. I tried SELECT, UPDATE, DELETE and INSERT and they all work fine. Nothing appears in the log trace. I changed the output back to info/default and it is all working fine.

The only difference I did in the last hour or so is that the connection string to the database (Azure SQL) previously did not have any database set, and I changed the default to a particular database. I wonder if that made it work fine.

![2024-05-29 at 4 34 PM](https://github.com/pacoweb/extraSqlScriptAs/assets/37816928/d9921646-5d3f-4d6f-8389-87416b9c718a)

**Comment by pacoweb** [comment] 2024-05-29 12:32
@sunilred Well seen! I'm going to investigate a little more. Thanks a lot!

**Comment by pacoweb** [comment] 2024-05-30 21:52
@sunilred I have published a new version of the extension (0.6.2). When you can, you could try to test it leaving the default database name in the connection window empty. Thank you!

**Comment by sunilred** [comment] 2024-05-31 00:43
Hi Paco, I tried the new version 0.6.2 and unfortunately, it still didn't work if the connection did not have the default database parameter set. It works fine if I assign a default database.

**Comment by pacoweb** [comment] 2024-05-31 03:46
@sunilred Oh, what a shame. I'll try again next week or look for help in the azuredatastudio repository. Thanks for the work!

**Comment by pacoweb** [comment] 2024-06-05 07:38
@sunilred y @patoJamriska 
I have uploaded a new version (0.6.3). The problem was not MacOs but the connection to Azure SQL Server instances. I have reproduced the problem and have been able to test the fix. If you can try it I would greatly appreciate it. Thanks! 
#22

**Comment by sunilred** [comment] 2024-06-17 02:57
Hi,

I have tested the 0.7 version against Azure SQL Server without a selecting a database and the extension now works as expected.

Thanks for fixing this.

Cheers
Sunil Reddy
Director - Data & Analytics Solutions
ReddInsight Limited | www.reddinsight.com <https://www.reddinsight.com/>
***@***.*** ***@***.***/> | +64 21 456 101

The contents of this email and any attachments are confidential and may be legally privileged. If you are not the intended recipient please advise the sender immediately and delete the email and attachments. Any use, dissemination, reproduction or distribution of this email and any attachments by anyone other than the intended recipient is prohibited.

**Comment by pacoweb** [comment] 2024-06-17 03:33
Fixed by #22

**Closed as completed by pacoweb** 2024-06-17 03:33 UTC
